# Generated by Django 6.0.1 on 2026-02-03 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reunion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("zoom_meeting_id", models.CharField(max_length=50, unique=True)),
                ("zoom_meeting_password", models.CharField(blank=True, max_length=20)),
                ("join_url", models.URLField()),
                ("start_url", models.URLField()),
                ("fecha_inicio", models.DateTimeField()),
                ("duracion", models.IntegerField()),
                (
                    "zona_horaria",
                    models.CharField(default="America/Hermosillo", max_length=50),
                ),
                ("sala_espera", models.BooleanField(default=True)),
                ("grabar_automaticamente", models.BooleanField(default=False)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "creador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Reuniones",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Participante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("asistio", models.BooleanField(default=False)),
                ("invitacion_enviada", models.BooleanField(default=False)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reunion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participantes",
                        to="reuniones.reunion",
                    ),
                ),
            ],
        ),
    ]
